files:
  include: 'sass/**/*.s+(a|c)ss'
  ignore:
    - 'sass/vendor/**/*.*'

# Rule Configuration
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-color-keywords: 1
  no-color-literals: 0
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties:
    - 1
    -
      exclude:
        - border
        - font-size
        - font-smoothing
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 0
  no-misspelled-properties: 1
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
  no-trailing-zero: 1
  no-transition-all: 0
  no-url-protocols: 1
  no-vendor-prefixes: 1
  no-warn: 0
  property-units: 0

  # nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 1
    -
      convention: 'hyphenatedbem'
  function-name-format: 0
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 0
  variable-name-format: 1

  # Style Guide
  bem-depth: 1
  border-zero: 1
  brace-style:
    - 1
    -
      style: 'stroustrup'
      allow-single-line: false
  clean-import-paths: 1
  empty-args: 0
  hex-length: 1
  hex-notation: 1
  indentation: 1
  leading-zero: 0
  nesting-depth:
    - 1
    -
      max-depth: 4
  property-sort-order: 0
  quotes:
    - 1
    -
      style: double
  shorthand-values: 1
  url-quotes: 0
  variable-for-property: 0
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 0

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
