# Docs: https://github.com/ucdavis/ucd-theme-tasks/blob/master/docs/config.md
# This config may be overridden by creating a gulp-config--custom.yml file
css:
  enabled: true
  src:
    - sass/**/*.scss
  vendor:
    - sass/vendor/**/*.css
  dest: dist/
  lint:
    enabled: false
  # tell the compiler whether you want 'expanded' or 'compressed' output code
  outputStyle: compressed

js:
  enabled: true
  src:
    - js/vendor/**/*.js
    - js/**/*.js
    - '!js/example.js'
  dest: dist/
  eslint:
    enabled: false
  #  Inform webpack that a library is being added via an external script tag.
#  externals:
#    jquery: 'jQuery'

nodeFiles:
  enabled: true

browserSync:
  enabled: true
  watchFiles:
    - '**/*.html'
  openBrowserAtStart: true
  # requires above to be true; allows non-default browser to open
  browser:
    - Google Chrome # on Windows use 'chrome'
